// Authentic Menus for Mutebites: Bheemasena Restaurant, A1 Biryani Point & Bismillah Fruit Juice

export const AUTHENTIC_RESTAURANTS = [
  {
    id: "bheemasena-restaurant",
    name: "Bheemasena Restaurant",
    description: "Biryani, Starters, Curries & More — Fast food and authentic biryanis for campus mood.",
    cuisine: "Biryani, Starters & Curries",
    location: "Campus Kitchen Hub, VIT-AP",
    phone: "8247075652",
    rating: 4.8,
    prep_time: "15-25 min",
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=1200&q=80",
    is_open: true
  },
  {
    id: "a1-biryani-point",
    name: "A1 Biryani Point",
    description: "Taste That Stays With You — 1000 ML Box Sufficient for One Person. Best Price, Best Taste.",
    cuisine: "Dum & Fry Biryanis",
    location: "Campus Kitchen Hub, VIT-AP",
    phone: "8247075652",
    rating: 4.9,
    prep_time: "10-20 min",
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80",
    is_open: true
  },
  {
    id: "bismillah-fruit-juice",
    name: "Bismillah Fruit Juice",
    description: "Pure Fresh Healthy — Freshness in Every Sip. Real Fruits, Real Goodness. Made for VIT-AP Students.",
    cuisine: "Fresh Fruit Juices & Sugarcane",
    location: "Campus Hub, VIT-AP",
    phone: "8247075652",
    rating: 4.9,
    prep_time: "5-10 min",
    image_url: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=1200&q=80",
    is_open: true
  }
];

export const AUTHENTIC_MENU_ITEMS = [
  // =========================================================================
  // 1. BHEEMASENA RESTAURANT
  // =========================================================================

  // Veg Starters
  {
    id: "bhm-vs-1",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Starters",
    name: "Veg Manchuria",
    description: "Golden crispy vegetable dumplings tossed in a savoury garlic, soya, and spring onion glaze.",
    price: 210,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.7
  },
  {
    id: "bhm-vs-2",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Starters",
    name: "Chilli Mushroom",
    description: "Fresh button mushrooms wok-tossed with capsicum, crunchy onions, and zesty green chilli seasoning.",
    price: 230,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.8
  },
  {
    id: "bhm-vs-3",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Starters",
    name: "Crispy Baby Corn",
    description: "Tender baby corn batter-fried to golden perfection and seasoned with spicy oriental spices.",
    price: 230,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.8
  },
  {
    id: "bhm-vs-4",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Starters",
    name: "Paneer 65",
    description: "Succulent paneer cubes tossed in Andhra spiced yogurt sauce, tempered with curry leaves and mustard.",
    price: 280,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.9
  },
  {
    id: "bhm-vs-5",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Starters",
    name: "Paneer Majestic",
    description: "Crispy paneer batons gently tossed in a creamy, velvety curd and fresh mint dressing.",
    price: 290,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.9
  },

  // Non-Veg Starters
  {
    id: "bhm-nvs-1",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Starters",
    name: "Chilli Chicken",
    description: "Tender marinated chicken chunks wok-seared with bell peppers, onions, and spicy dark soya sauce.",
    price: 290,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1625938145744-e380515399b7?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvs-2",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Starters",
    name: "Chicken Manchuria",
    description: "Juicy chicken meatballs simmered in a hot, sweet and spicy Indo-Chinese ginger-garlic sauce.",
    price: 290,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.8
  },
  {
    id: "bhm-nvs-3",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Starters",
    name: "Chicken 65",
    description: "Authentic spicy deep-fried chicken tossed with green chillies, curry leaves, and Southern spices.",
    price: 290,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvs-4",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Starters",
    name: "Chicken Majestic",
    description: "Royal Hyderabad-style shredded chicken strips dry-spiced and finished with curd, mint, and cilantro.",
    price: 290,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.9
  },

  // Veg Biryani
  {
    id: "bhm-vb-1",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Biryani",
    name: "Special Paneer Biryani",
    description: "Fragrant saffron basmati rice slow-cooked and layered with tender marinated paneer tikka cubes.",
    price: 290,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.8
  },
  {
    id: "bhm-vb-2",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Biryani",
    name: "Special Mushroom Biryani",
    description: "Juicy button mushrooms infused with whole spices and layered over long-grain dum basmati rice.",
    price: 290,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.8
  },
  {
    id: "bhm-vb-3",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Biryani",
    name: "Special Veg Biryani",
    description: "Wholesome seasonal vegetables slow-cooked in handi with fragrant spices and saffron rice.",
    price: 260,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.7
  },
  {
    id: "bhm-vb-4",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Biryani",
    name: "Ulavacharu Biryani",
    description: "Traditional Andhra delicacy: rich horse-gram broth (ulavacharu) cooked into aromatic biryani rice.",
    price: 270,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.9
  },
  {
    id: "bhm-vb-5",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Biryani",
    name: "Kaju Biryani",
    description: "Delectable biryani loaded with golden roasted cashews, caramelized onions, and fragrant herbs.",
    price: 290,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.9
  },
  {
    id: "bhm-vb-6",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Biryani",
    name: "Special Kaju Biryani",
    description: "Royal treat enriched with extra premium roasted cashews and rich chef special biryani gravy.",
    price: 310,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 5.0
  },

  // Non-Veg Biryani
  {
    id: "bhm-nvb-1",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Special Egg Biryani",
    description: "Fragrant dum biryani rice served with golden-crusted pan-fried eggs and spiced biryani gravy.",
    price: 280,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.8
  },
  {
    id: "bhm-nvb-2",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Chicken Dum Biryani",
    description: "Authentic slow-dum cooked basmati rice layered with juicy, marinated chicken on the bone.",
    price: 270,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvb-3",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Kundan Biryani",
    description: "Grand signature royal biryani cooked with succulent chicken, rich dry fruits, and aromatic essence.",
    price: 360,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 5.0
  },
  {
    id: "bhm-nvb-4",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Chicken Fry Biryani",
    description: "Classic flavorful biryani rice topped with spicy Andhra crispy fried chicken pieces.",
    price: 280,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvb-5",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Special Chicken Biryani",
    description: "Tender boneless chicken morsels cooked in rich masala gravy served over hot aromatic biryani rice.",
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvb-6",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Joint Biryani",
    description: "Succulent whole chicken leg joint roasted with coastal spices served over fragrant dum biryani.",
    price: 310,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvb-7",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Chicken Mughlai Biryani",
    description: "Rich and creamy Mughlai chicken cooked with egg ribbons, cashews, and aromatic spices.",
    price: 330,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvb-8",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Chicken Lollipop Biryani",
    description: "Golden fried crispy chicken lollipops served on a bed of mouthwatering spiced dum biryani.",
    price: 330,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvb-9",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Biryani",
    name: "Gongura Chicken Fry Biryani (Thursday Only)",
    description: "Special Thursday edition: tangy, fiery Andhra gongura leaf chicken fry over fragrant biryani.",
    price: 320,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "20-25 mins",
    rating: 5.0
  },

  // Single Biryani
  {
    id: "bhm-sb-1",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Single Biryani",
    name: "Single Dum Biryani",
    description: "Personal portion of authentic chicken dum biryani, sufficient for one person.",
    price: 190,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.8
  },
  {
    id: "bhm-sb-2",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Single Biryani",
    name: "Single Fry Biryani",
    description: "Single-serving biryani rice topped with crispy spiced chicken fry piece.",
    price: 200,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.8
  },
  {
    id: "bhm-sb-3",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Single Biryani",
    name: "Single Special Biryani",
    description: "Single portion of boneless chicken special biryani with rich savory masala.",
    price: 220,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.9
  },
  {
    id: "bhm-sb-4",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Single Biryani",
    name: "Single Paneer Biryani",
    description: "Single portion size aromatic biryani rice served with fresh spiced paneer cubes.",
    price: 200,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.8
  },
  {
    id: "bhm-sb-5",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Single Biryani",
    name: "Single Mushroom Biryani",
    description: "Single portion of flavorful biryani rice tossed with button mushrooms and spices.",
    price: 220,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.7
  },
  {
    id: "bhm-sb-6",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Single Biryani",
    name: "Single Mughlai Biryani",
    description: "Single-serving rich Mughlai chicken biryani with spiced egg gravy.",
    price: 220,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.8
  },
  {
    id: "bhm-sb-7",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Single Biryani",
    name: "Single Gongura Biryani (Thursday Only)",
    description: "Single portion size spicy, tangy Gongura chicken fry biryani (Available on Thursdays).",
    price: 230,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.9
  },
  {
    id: "bhm-sb-8",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Single Biryani",
    name: "Mixed Biryani",
    description: "Delicious combination of chicken pieces and egg cooked into authentic biryani rice.",
    price: 220,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.8
  },

  // Breads
  {
    id: "bhm-br-1",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Breads",
    name: "Butter Naan",
    description: "Fluffy leavened oven-baked flatbread generously brushed with creamy dairy butter.",
    price: 45,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10 mins",
    rating: 4.8
  },
  {
    id: "bhm-br-2",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Breads",
    name: "Roti",
    description: "Traditional whole wheat tandoori flatbread, light and freshly roasted.",
    price: 25,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10 mins",
    rating: 4.7
  },

  // Veg Curries
  {
    id: "bhm-vc-1",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Curries",
    name: "Paneer Butter Masala",
    description: "Soft paneer cubes simmered in a velvety tomato, cashew, and butter makhani gravy.",
    price: 280,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.9
  },
  {
    id: "bhm-vc-2",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Veg Curries",
    name: "Kaju Paneer Butter Masala",
    description: "Golden roasted cashew nuts and tender paneer bathed in rich Mughlai butter curry.",
    price: 300,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 5.0
  },

  // Non-Veg Curries
  {
    id: "bhm-nvc-1",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Curries",
    name: "Egg Burji",
    description: "Spicy scrambled eggs tempered with caramelized onions, fresh green chillies, and coriander.",
    price: 190,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.8
  },
  {
    id: "bhm-nvc-2",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Curries",
    name: "Butter Chicken",
    description: "Succulent chicken cooked in a rich, mildly sweet and creamy tomato-butter sauce.",
    price: 290,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.9
  },
  {
    id: "bhm-nvc-3",
    restaurant_id: "bheemasena-restaurant",
    restaurant_name: "Bheemasena Restaurant",
    category: "Non-Veg Curries",
    name: "Chicken Curry",
    description: "Homestyle Andhra spiced chicken curry prepared with freshly ground masala and aromatic curry leaves.",
    price: 270,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    preparation_time: "15-20 mins",
    rating: 4.8
  },

  // =========================================================================
  // 2. A1 BIRYANI POINT (Taste That Stays With You - 1000ml Box Portion)
  // =========================================================================
  {
    id: "a1-dum-biryani",
    restaurant_id: "a1-biryani-point",
    restaurant_name: "A1 Biryani Point",
    category: "Biryani Specials",
    name: "A1 Biryani Dum Biryani",
    description: "1000 ML BOX — Sufficient for One Person. Slow-cooked authentic dum chicken biryani packed with tender meat, eggs and aroma.",
    price: 190,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.9
  },
  {
    id: "a1-fry-pieces-biryani",
    restaurant_id: "a1-biryani-point",
    restaurant_name: "A1 Biryani Point",
    category: "Biryani Specials",
    name: "A1 Biryani Fry Pieces Biryani",
    description: "1000 ML BOX — Sufficient for One Person. Fragrant biryani rice served with hot, crispy spiced chicken fry pieces.",
    price: 200,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 4.9
  },
  {
    id: "a1-mixed-biryani",
    restaurant_id: "a1-biryani-point",
    restaurant_name: "A1 Biryani Point",
    category: "Biryani Specials",
    name: "A1 Biryani Mixed Biryani",
    description: "1000 ML BOX — Sufficient for One Person. Grand combination of chicken pieces and egg cooked into flavorful biryani rice.",
    price: 210,
    is_veg: false,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    preparation_time: "10-15 mins",
    rating: 5.0
  },

  // =========================================================================
  // 3. BISMILLAH FRUIT JUICE (Pure Fresh Healthy - Freshness in Every Sip)
  // =========================================================================

  // Fresh Fruit Juices
  {
    id: "bj-fj-carrot",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Carrot Juice",
    description: "100% natural, freshly pressed farm-fresh carrot juice. Rich in Vitamin A with zero added preservatives.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.8
  },
  {
    id: "bj-fj-beetroot",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Beetroot Juice",
    description: "Detoxifying and revitalizing freshly squeezed beetroot juice. Pure natural energy booster.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.8
  },
  {
    id: "bj-fj-pineapple",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Pineapple Juice",
    description: "Sweet, tangy and zesty tropical pineapple juice made from fresh sun-ripened pineapples.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.9
  },
  {
    id: "bj-fj-grape",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Grape Juice",
    description: "Chilled fresh black grape juice packed with natural sweetness and antioxidants.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.8
  },
  {
    id: "bj-fj-pomegranate",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Pomegranate Juice",
    description: "Freshly cold-pressed ruby red pomegranate (Anaar) pearls. 100% natural and healthy.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 5.0
  },
  {
    id: "bj-fj-apple",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Apple Juice",
    description: "Crisp and refreshing juice freshly squeezed from whole juicy orchard apples.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.8
  },
  {
    id: "bj-fj-muskmelon",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Muskmelon Juice",
    description: "Naturally sweet, fragrant and cooling muskmelon (kharbuja) juice.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.8
  },
  {
    id: "bj-fj-watermelon",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Watermelon Juice",
    description: "Ultra-hydrating summer refresher prepared from fresh crimson watermelons.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.9
  },
  {
    id: "bj-fj-banana",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Banana Juice",
    description: "Creamy, wholesome and filling fresh banana smoothie shake.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.7
  },
  {
    id: "bj-fj-sweet-lemon",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Sweet Lemon (Mosambi)",
    description: "Freshly squeezed citrus mosambi juice with a dash of black salt and natural freshness.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 4.9
  },
  {
    id: "bj-fj-bottle",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Fruit Juices",
    name: "Any Fruit Juice Bottle",
    description: "Full take-away travel friendly sealed bottle (approx 500ml) of your choice of fresh fruit juice.",
    price: 130,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 5.0
  },

  // Sugarcane Juice
  {
    id: "bj-sc-glass",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Sugarcane Juice",
    name: "Sugarcane Juice (Glass)",
    description: "Freshly pressed sugarcane juice infused with ginger, lemon, and cooling mint leaves.",
    price: 40,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5 mins",
    rating: 4.9
  },
  {
    id: "bj-sc-bottle",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Sugarcane Juice",
    name: "Sugarcane Juice (1 Bottle)",
    description: "Full chilled bottle of freshly pressed sugarcane juice with ginger, lemon and mint.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5 mins",
    rating: 5.0
  },

  // Special
  {
    id: "bj-sp-special",
    restaurant_id: "bismillah-fruit-juice",
    restaurant_name: "Bismillah Fruit Juice",
    category: "Special",
    name: "Bismillah Fruit Juice (Any Flavour)",
    description: "Cool, refreshing & healthy chef-special mixed fruit campus delight.",
    price: 80,
    is_veg: true,
    is_available: true,
    image_url: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80",
    preparation_time: "5-10 mins",
    rating: 5.0
  }
];
